apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:IaH84/f5zFlq2sqA,iv:n+9T90nEcTQ5uBsTb119tnzg/B6icsL9w1dAFNLG5ZQ=,tag:3/hY5RQPRrO+eIvoov7kcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f354u34jhu69un4wq3wx3akyt569ewjhu7d5ysgum09mhwxlxdmq7pfptz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Slc5NC9QZ3JTa0wwMGc3
            NFoxTFVZNVFFUTQ0cWphajcxRkpQQ0laa1RBCmUzWlZCR2pTWXVnZXNReENQbFBk
            WDlvNWgxbXBoMlFJWWVtWk5zbjltUlUKLS0tIHlqb1QzRjdDdDJUaTlaZGplNmpI
            cWwrTzA1T0xhZWRnN09kZDV4eERZUGcKnclUstroVRD+CLkqiPxVA07E33QyUaTz
            b9+mH+Pwn7ZYk8/GHSPC+a2Y1AuiJaGlsmw/QdD2Rj3WcXPkziqtfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-09T00:49:16Z"
    mac: ENC[AES256_GCM,data:h3rVYS/1J2TLtqjORm6wF7irT0svYStg9m62wSxdJwizn6jNv4g2sEEqSHIzHn7n09vGaBUOAKzxoq+e5hbvADL7woUG+4upG/3xwmBz5yldkpgeAox73WR9qgz0Op3rlCnsh772cwGTpJnH57jZ7SHUXhENeHf39ko+523+Q+0=,iv:xn/cKWn8wiNWtXJ7v0+X8/uRjQqstfxnPFi/l36U6aw=,tag:TYnLASWAb+A1TLmhjKxGnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
